version: "3.8"

services:
  database:
    container_name: strava_database
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - strava_network
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data:

networks:
  strava_network:
