name: Run Python script on schedule

on:
  schedule:
    - cron: '* * * * *'  # toutes les heures à la minute 0
  workflow_dispatch:  # permet de lancer manuellement aussi

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # ou ta version préférée

      - name: Install dependencies
        run: pip install -r requirement.txt

      - name: Write config.json from secret
        run: echo '${{ secrets.CONFIG_JSON }}' > config.json

      - name: Run script
        run: python recuperation_activites.py
